config/routes.rb
Rails.application.routes.draw do
  resources :authors
  get 'pages/home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: [:show, :edit, :update, :destroy]

  # GET /authors
  # GET /authors.json
  def index
    @authors = Author.all
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
  end

  # GET /authors/new
  def new
    @author = Author.new
  end

  # GET /authors/1/edit
  def edit
  end

  # POST /authors
  # POST /authors.json
  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: 'Author was successfully created.' }
        format.json { render :show, status: :created, location: @author }
      else
        format.html { render :new }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authors/1
  # PATCH/PUT /authors/1.json
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to @author, notice: 'Author was successfully updated.' }
        format.json { render :show, status: :ok, location: @author }
      else
        format.html { render :edit }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1
  # DELETE /authors/1.json
  def destroy
    @author.destroy
    respond_to do |format|
      format.html { redirect_to authors_url, notice: 'Author was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def author_params
      params.require(:author).permit(:name, :birthdate)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/authors/_form.html.erb
<%= form_for(author) do |f| %>
  <% if author.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(author.errors.count, "error") %> prohibited this author from being saved:</h2>

      <ul>
      <% author.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :birthdate %>
    <%= f.date_select :birthdate %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/authors/edit.html.erb
<h1>Editing Author</h1>

<%= render 'form', author: @author %>

<%= link_to 'Show', @author %> |
<%= link_to 'Back', authors_path %>

app/views/authors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Authors</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Birthdate</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @authors.each do |author| %>
      <tr>
        <td><%= author.name %></td>
        <td><%= author.birthdate %></td>
        <td><%= link_to 'Show', author %></td>
        <td><%= link_to 'Edit', edit_author_path(author) %></td>
        <td><%= link_to 'Destroy', author, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Author', new_author_path %>

app/views/authors/new.html.erb
<h1>New Author</h1>

<%= render 'form', author: @author %>

<%= link_to 'Back', authors_path %>

app/views/authors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @author.name %>
</p>

<p>
  <strong>Birthdate:</strong>
  <%= @author.birthdate %>
</p>

<%= link_to 'Edit', edit_author_path(@author) %> |
<%= link_to 'Back', authors_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
      <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <%= yield %>

  </body>
</html>

app/views/pages/home.html.erb
<header class="header">

    <div class="title-bar" data-responsive-toggle="monmenu">
        <button class="menu-icon" type="button" data-toggle></button>
        <div class="title-bar-title">Lorent Pascal Informatique</div>
    </div>


<div class="top-bar" id="monmenu">
    <div class="top-bar-title">
        LORENT PASCAL INFORMATIQUE
    </div>
    <div class="top-bar-right">
        <ul class="dropdown menu vertical medium-horizontal" data-dropdown-menu>
            <li><a href="#">SERVICES</a></li>
            <li><a href="#">TARIFS</a></li>
            <li><a href="#">ADRESSE</a></li>
            <li><a href="#">CONTACT</a></li>
        </ul>
    </div>

</div>

    <br/>
    <br/>
    <div class="row">
        <div class="small-12 medium-8 columns">
            <h1>Dépannage Informatique à Domicile</h1>
          Intervention sur tout type de support, pc et portable.
            <br> <br> <br> <br><br><br>
            <br>
            <br>

            <div class="small-12 medium-6 columns">
                <div class="button white">02 41 74 18 01</div>
            </div>

            <div class="small-12 medium-6 columns">
                <a href="mailto:lorent.pascal@neuf.fr" class="button large white btn">Devis gratuit</a>
            </div>

        </div>


        <!--   -------------------- newsletter ------------------- -->

        <div class="small-12 medium-4 columns">

            <div class="callout sucess">
                <div class="button">Inscrivez vous à ma newsletter</div>
                <label>Prénom
                    <input type="text" placeholder="Prenom">
                </label>
                <label>Nom
                    <input type="text" placeholder="Prenom">
                </label>
                <label>Nom
                    <input type="text" placeholder="Adresse Email">
                </label>
                <div class="button submit">Inscription</div>
            </div>
        </div>
    </div>
    </div>


    <br/>
    <br/>
    <br/>

</header>


<main class="content">


    <!--   -------------------- serices ------------------- -->


    <section id="service" class="service">
        <div class="row">
            <div class="small-12 medium-8 columns">
                <h2>Nos Services</h2>
                <br>
                <ul>
                    <li>Diagnostic pour panne de matériel</li>
                    <li>Réparation de PC, Portable toute marques.</li>
                    <li>Néttoyage, optimisation, suppression de virus de votre système</li>
                    <li>Sauvegarde de vos données(documents...)</li>
                    <li>Réintégration de vos données dans votre système</li>
                    <li>Réinstallation de votre système d’exploitation (windows, linux )</li>
                    <li>Installation périphérique (Box, wifi, ethernet…)</li>
                </ul>
            </div>

            <div class="small-12 medium-4 columns">
                <div class="callout">

                    <%= image_tag("docteur.jpg", :alt => "docteur feed") %>
                </div>
            </div>
    </section>


    <!--   -------------------- tarifs ------------------- -->

    <section id="tarif" class="tarif">
        <div class="row">

            <div class="small-12 medium-8 columns">
                <h2>Nos tarifs</h2>
                <br>
                <p> TOUS LES SERVICES individuellement, que ce soit un dépannage ou une installation sont facturé 30€/H hors prix des pièces de rechange.</p>
                <p>Cela inclut:</p>
               <ul>
                <li>Récupération des données</li>
                <li>Réintégration des données</li>
                <li>Réinstallation de votre système</li>
                <li>Installation réseau</li>

                </ul>

                <p>Le prêt de matériel le temps des travaux est un service LORENT Pascal facturé 15€.</p>
            </div>

            <div class="small-12 medium-4 columns">
                <div class="callout">


                        <%= image_tag("reparation.jpg", :alt => "reparation feed") %>


                </div>
            </div>
        </div>
    </section>

    <!--   -------------------- Adresse ------------------- -->
    <section id="adresse" class="adresse">

        <div class="row">
            <div class="small-12 medium-4 columns">
                <div class="callout">
                    <h2>Adresse</h2>
                    <p><strong>LORENT Pascal Informatique</strong></p>
                    <p>11 Chemin de Marigné <br>
                        49250 Fontaine Gérin</p>
                    <p>Email: <a href="mailto:lorent.pascal@neuf.fr">lorent.pascal@neuf.fr</a></p>

                </div>
            </div>
            <div class="small-12 medium-8 columns">
                <!--   <div class="carte"> -->

                <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d21570.189951587017!2d-0.1902617926064241!3d47.48458036341648!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x4808085e3e68fb69%3A0xa561b55e4f9e29e4!2sLorent+Pascal!5e0!3m2!1sfr!2sfr!4v1487845791521" width="700" height="235" frameborder="0" style="border:0" allowfullscreen></iframe>

                <!--     </div> -->
            </div>
        </div>
    </section>

    <!--   --------------------deplacement------------------- -->

    <div class="row">

        <div class="callout">
            Tous les dépannages à domicile sont gratuits dans un rayon de 10km autour de Beaugé puis payant jusqu'à 30km.
        </div>
    </div>

</main>

    <!--   --------------------Inter------------------- -->
    <div class="inter">
        <br>  <br>
        <div class="row">
            <div class="small-6 medium-6 columns">
                <a href="mailto:lorent.pascal@neuf.fr" class="button large white btn">Devis gratuit</a>
            </div>
        </div>
        <br>
    </div>


    <!--   --------------------Footer------------------- -->

    <footer class="footer">
        <div class="row">

            <div class="small-12 medium-4 columns">
                <br/>
                <h4>Informations utiles</h4>
            </div>




            <div class="small-12 medium-4 columns">
                <br/>
                <h4>  Nos coordonnées</h4>
                <p>Tél: 02 41 74 18 01 <br>
                    Port: 06 70 88 28 44</p>
                <hr>
                <p>adresse: <br>
                    11 Chemin de Marigné <br>
                    49250 Fontaine Gérin </p>
                <hr>
                <p>Email: <br>lorent.pascal@neuf.fr</a>
            </div>
            <div class="small-12 medium-4 columns">
                <br/>
                <h4>Abonnez vous à notre info lettre</h4>
                <label> <br/>
                    <input type="text" placeholder="Prenom">
                </label>
                <label> <br/>
                    <input type="text" placeholder="Prenom">
                </label>
                <label> <br/>
                    <input type="text" placeholder="Adresse Email">
                </label>
                <div class="button submit">Inscription</div>
            </div>
        </div>
        </div>
    </footer>

    <div class="copy">
        <div class="row">

         <span> copyright: Lorent Pascal Dépannage Informatique</span>
        </div>
    </div>